//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerSystem
    {
        public int Id { get; set; }
        public int customerId { get; set; }
        public string customerAccess { get; set; }
        public int systemId { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual systemsDetail systemsDetail { get; set; }
    }
}
